### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by dbrgn** [gfroerli/api#138]
I'd suggest AGPL.

What do you think, @rnestler @schmijos ?

**Comment by rnestler** [comment]
Could there be compatibility issues when using AGPL with dependencies?

**Comment by dbrgn** [comment]
> Could there be compatibility issues when using AGPL with dependencies? If not I agree.

As long as we only use dependencies that are permissively licensed (MIT/BSD/etc) or GPL as well, it shouldn't be an issue.

**Comment by dbrgn** [comment]
The AGPL ensures that modifications must be published and freely licensed, in case someone makes modifications to the server and hosts that server under a public URL. I think that's slightly better for a hackerspace project than a permissive license 🙂

Thanks for the replies!
