### ISSUE TITLE
Type of temperature measurement

### ISSUE THREAD

**Issue by dbrgn** [gfroerli/api#27]
A temperature measurement currently looks like this:

```javascript
    {
        "created_at": "2017-05-01T21:49:38.971Z",
        "custom_attributes": null,
        "id": 57,
        "sensor_id": 3,
        "temperature": "25.5625",
        "url": "https://watertemp-api.coredump.ch/api/measurements/57"
    },
```

Is there a reason why the temperature is a string? Why not a float?

**Comment by schmijos** [comment]
The reason is, that temperature is of a decimal type in the database. I can change it to a float. Ok @dbrgn ?

**Comment by dbrgn** [comment]
Yes, float is OK :) The application can deal with rounding.
