### ISSUE TITLE
General Improvements of API

### ISSUE THREAD

**Issue by Makram95** [gfroerli/api#64]
Hello everyone!
I'm currently working on the iOS application for gfrör.li and during API implementation I came up with the following QoL improvements. I talked to Danilo yesterday and he told me to post these here :) 

General:
- [x]  small Documentation for people who can't decifer Ruby on rails in reasonable time ;)
- [x] the temps as floats and the dates in a better format
- [x] order in json file still wrong
- [ ] sensor description/sponsor multi language?

Sensors:
- [x] Query Param for "id" to request only one sensor, eg: `https://watertemp-api.coredump.ch/api/sensors?id=1`
- [x] highest and lowest Measurement ever recorded (might already be possible see point 1 of General above)
- [x] decouple sending all measurement ID's with sensor request. For sensor with ID 1, it contains almost 65k values. Maybe consider something like: `https://watertemp-api.coredump.ch/api/sensors/measurement-ids?sensor-id=1`
- [ ] add a field for the name of the waterbody the sensor is placed in, and possibility to request all sensors of it with one request

Measurements:
- [x] To draw nice graphs faster, it would be nice to be able to request already prepared data, so API calls that give you the last 'x' hourly avg temperatures (x=24 for a day, x= 168 for a week) and the last 'x' daily avg temperatures (x= 30 for a month, x=365 for a year), maybe even just as an array of floats, if they are ordered
- [x] What is the purpose of the "updated_at" for measurements?

Sponsors:
- [x] Query Param for "id" to request only one sponsor, eg: `https://watertemp-api.coredump.ch/api/sponsors?id=1`

I hope some of these are possible to implement :)
Marc

**Comment by dbrgn** [comment]
> small Documentation for people who can't decifer Ruby on rails in reasonable time ;)

Yes, that would be great :slightly_smiling_face: 

> dates in a better format

See #54.

> the temps as floats

See #27.

> order in json file still wrong

Should get fixed by #63 I think. Tracking issue is #40.

> decouple sending all measurement ID's with sensor request

I think this would be fixed in a more generic way with #41.

**Comment by Makram95** [comment]
@dbrgn Cool, thx for the clarifications!

**Comment by Makram95** [comment]
Will replace open points with new issues.
