### ISSUE TITLE
App Endpoints: Add sponsor_id to sensors list

### ISSUE THREAD

**Issue by dbrgn** [gfroerli/api#77]
When opening the sensor details pane in the app, I can load the sensor details and the sponsor details in parallel:

GET /api/mobile_app/sensors/1
GET /api/mobile_app/sensors/1/sponsor

Multiple sensors may share the same sponsor, so it could be cached. However, when opening the sensor details, I do not know yet who the sponsor is, so I don't have a cache key.

Feature request: Add the sponsor_id to the `/api/mobile_app/sensors/` endpoint as well! This way, we have a lookup key for the sponsors and can cache them.

**Comment by schmijos** [comment]
Not sure if I understand the request correctly. You would like to use `sponsor_id` in the sensor listing to populate a second tab in the app? Wouldn't that rather require a sponsor listing?

**Comment by dbrgn** [comment]
The idea: I open the sensor details, with an initially empty sponsor cache. I do the following two requests in parallel:

GET /api/mobile_app/sensors/1
GET /api/mobile_app/sensors/1/sponsor

Now I know that the sponsor of the sensor 1 is "Evil Corp", with sponsor id 666. I put that sponsor information in my cache.

If I now close the details, and open the details of the sensor 7, whic his also sponsored by Evil Corp, I could load the sponsor information from cache. But only if I know in advance, that they are sponsoring sensor 7. For this, I need the sponsor id in the sensor list.

Thanks for implementing the change!
