### ISSUE TITLE
Decrease size of Docker image

### ISSUE THREAD

**Issue by dbrgn** [gfroerli/api#97]
The Docker image is currently 1.16 GiB in size. That's huge.

We could reduce the size by using a smaller base image.

- Option A: `2.7.2-slim-buster` (or a later version, possibly with `slim-bullseye`)
- Option B: `2.7.2-alpine3.13` (or a newer alpine version, if available for a newer ruby version)

@schmijos are there any issues with running Rails applications on Alpine (e.g. due to native extensions)?

**Comment by schmijos** [comment]
There shouldn't be an issue since we're not using special dependencies. I think the only one is _libxml2_.

**Comment by dbrgn** [comment]
Maybe also the database driver (through libpq). Do Ruby gems ship binary components? If yes, is there a platform target for Alpine?

**Comment by schmijos** [comment]
They don't. You can use `platform: :ruby` explicitly to force building from source.
